services:
  app:
    build:
      context: .
      dockerfile: dockerfile
      target: builder
    image: video-streaming-builder
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=db-pass
      - DB_NAME=postgres
    depends_on:
      - db
    volumes:
      - ./resources:/app/resources
      - ./sql:/app/sql
    networks:
      - video-streaming-network
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=db-pass
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - video-streaming-network
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

networks:
  video-streaming-network:
    driver: bridge

volumes:
  postgres_data: